language: node_js
node_js:
 - '8'
env:
  CC_TEST_REPORTER_ID:5ad41c88ae246e330920563147629b21ea1e0bf8e3798b9890df347fbd7f4bc2

global:
 - export NODE_ENV=test

before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- npm run coverage
